name: faultproduct
channels:
- conda-forge
- defaults
dependencies:
- jupyter
- impactutils
- ipython
- spyder
- libcomcat
- lxml
- matplotlib
- numpy
- pytest
- pytest-cov
- python=3.5
- openpyxl
- openquake.engine
